{"name":"Receive user with wrong id","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected status code and actual weren't equals; expected [400] but found [200]","trace":"java.lang.AssertionError: expected status code and actual weren't equals; expected [400] but found [200]\n\tat org.testng.Assert.fail(Assert.java:99)\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\n\tat org.testng.Assert.assertEquals(Assert.java:122)\n\tat org.testng.Assert.assertEquals(Assert.java:907)\n\tat restservice.helpers.AssertionsHelper.assertStatusCodeBadRequestNegative(AssertionsHelper.java:24)\n\tat restservice.helpers.AssertionsHelper.assertStatusCodeBadRequestNegative(AssertionsHelper.java:20)\n\tat restservicetest.GetUserTest.getUserNegativeTest(GetUserTest.java:56)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\n\tat org.testng.TestRunner.run(TestRunner.java:585)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\n\tat org.testng.TestNG.run(TestNG.java:1037)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Get of user with wrong id","steps":[],"attachments":[{"name":"Request","source":"2e4ada00-f5b5-409b-9482-a251b1a6e3c1-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 ","source":"cb1bb66b-2b6e-4cd5-8b27-55c2a5dc0429-attachment.html","type":"text/html"}],"parameters":[],"start":1694700928661,"stop":1694700929644,"uuid":"03bfad3a-01ca-498b-bc2d-b76508e56411","historyId":"52638f72ebdd334c80d6e9ce03ecc2f2","fullName":"restservicetest.GetUserTest.getUserNegativeTest","labels":[{"name":"package","value":"restservicetest.GetUserTest"},{"name":"testClass","value":"restservicetest.GetUserTest"},{"name":"testMethod","value":"getUserNegativeTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"User-controler-gradle"},{"name":"subSuite","value":"restservicetest.GetUserTest"},{"name":"host","value":"SPR-LT-014"},{"name":"thread","value":"34312@SPR-LT-014.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}